version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.12
    working_directory: /go/src/github.com/otiai10/too
    steps:
      - checkout
      - run: go get -v -t -d ./...
      - run: go test -v ./...
      # TODO: Fix race data detection
      # - run: go test ./... -race -coverprofile=coverage.txt -covermode=atomic
      - run: go test ./... -coverprofile=coverage.txt -covermode=atomic
      - run: bash <(curl -s https://codecov.io/bash)